//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.Cargoes = new HashSet<Cargo>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int RouteId { get; set; }
        public Nullable<int> TruckId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<decimal> PriceOfShipment { get; set; }
        public Nullable<decimal> PriceOfTotalCargo { get; set; }
    
        public virtual DriverTruck DriverTruck { get; set; }
        public virtual RouteOfCargo RouteOfCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargoes { get; set; }
    }
}
