SET IDENTITY_INSERT [dbo].[RouteOfCargo] ON
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (2, 1, 1, 1)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (4, 1, 5, 2865.3)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (5, 1, 6, 1034.4)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (6, 1, 7, 2436.8)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (7, 1, 8, 2886.4)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (8, 1, 9, 2749)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (9, 1, 10, 2571.3)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (10, 1, 11, 513.2)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (11, 1, 12, 251.6)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (12, 1, 13, 844.6)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (13, 1, 14, 2953.8)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (14, 1, 15, 2446.6)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (15, 1, 16, 2762.4)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (16, 1, 17, 659.7)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (17, 1, 18, 1722.4)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (18, 1, 19, 2773.1)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (19, 1, 20, 1757.2)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (20, 1, 21, 1483)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (21, 1, 22, 2303)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (22, 1, 23, 342)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (23, 1, 24, 1176.4)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (24, 1, 25, 2359.9)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (25, 1, 26, 642.2)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (26, 1, 27, 1731.5)
INSERT INTO [dbo].[RouteOfCargo] ([Id], [OriginWarehouseId], [DestinationWarehouseId], [Distance]) VALUES (27, 1, 28, 1047.8)
SET IDENTITY_INSERT [dbo].[RouteOfCargo] OFF
